### ISSUE TITLE
Fix crashing issue when entering an invalid number on certain menus

### ISSUE THREAD

**Issue by hhaslam11** [hhaslam11/Text-Fighter#52]
The equip weapon menu,
the equip armour menu.
the eat food menu, 
the equip weapon menu.

For example, the `equip weapon` menu:

> 1) Fists
> 2) Baseball Bat
> 3) Knife
> 4) Pipe
> 5) Pistol
> 6) Smg
> 7) Shotgun
> 8) Rifle
> 9) Sniper
> 10
> Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
>   at java.util.ArrayList.rangeCheck(ArrayList.java:653)
>   at java.util.ArrayList.get(ArrayList.java:429)
>   at com.hotmail.kalebmarc.textfighter.main.Weapon.choose(Weapon.java:141)
>   at com.hotmail.kalebmarc.textfighter.main.Game.home(Game.java:282)
>   at com.hotmail.kalebmarc.textfighter.main.Game.start(Game.java:146)
>   at com.hotmail.kalebmarc.textfighter.main.Menu.load(Menu.java:29)
>   at com.hotmail.kalebmarc.textfighter.main.Start.main(Start.java:19)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
> 
> Process finished with exit code 1

**Comment by hhaslam11** [comment]
Can't seem to reproduce this. I probably fixed it sometime and forgot to close this issue.
